[pupil]
name=circle_25m
arraySize=182
diameterPixels=182
diameterMeters=25.4
centralObscuration=0

[simulation]
trials=10000
oversize=3
wavelength=0.8e-6

[atmosphere]
seeing=0.790
seeingWavelength=500e-9
outerScale=0
subharmonicLevel=1
outerSubHarmonics=true
psdSubtractPiston=true
psdSubtractTipTilt=false

[basis]
type=zernike
name=zernike
modes=1000
cutoffs=default
fit=pinv
pinvAlpha=0.001
pinvMaxCondition=1e6

[analysis]
maxFourierM=91

[output]
directory=output/circle_25m
label=circle_25m
writePupil=true
writeBasis=false
writePhaseScreens=true
