[pupil]
file=/home/jrmales/Source/mxWork/GMT/pupil/gmt-pupil-182x182.fits
name=gmt_25m
diameterPixels=182
diameterMeters=25.4
threshold=0.5

[simulation]
trials=10000
threads=0
oversize=0
wavelength=0.8e-6

[atmosphere]
seeing=0.790
seeingWavelength=500e-9
outerScale=0
subharmonicLevel=8
outerSubHarmonics=true
subharmonicPrecalc=false
psdSubtractPiston=false
psdSubtractTipTilt=false

[basis]
type=zernike
name=zernike
modes=1000
cutoffs=default
fit=pinv
pinvAlpha=0.001
pinvMaxCondition=1e6
smoothingFwhm=12.5
smoothingStart=100
lowPassCutoff=0

[analysis]
maxFourierM=-1

[output]
directory=output/gmagaox_stroke_exploration/gmt_25m_fwhm12p5
label=gmt_25m_fwhm12p5
writePupil=false
writeBasis=false
writePhaseScreens=false
