[pupil]
file=/home/jrmales/Source/mxWork/GMT/pupil/gmt-pupil-182x182.fits
name=gmt_25m
diameterPixels=182
diameterMeters=25.4
threshold=0.5

[simulation]
trials=10000
threads=0
oversize=0
wavelength=0.8e-6

[atmosphere]
seeing=0.790
seeingWavelength=500e-9
outerScale=0
subharmonicLevel=8
outerSubHarmonics=true
subharmonicPrecalc=false
psdSubtractPiston=false
psdSubtractTipTilt=false

[basis]
type=hybrid
name=gmt_25m_hybrid_z2to10_fourierRectN32
modes=-1
cutoffs=0,9,17,33,89,297,1097
fit=pinv
pinvAlpha=0.001
pinvMaxCondition=1e6
smoothingFwhm=0
smoothingStart=100
lowPassCutoff=0
hybridZernikeMin=2
hybridZernikeMax=10
hybridFourierN=32

[analysis]
maxFourierM=-1

[output]
directory=output/gmagaox_stroke_exploration_hybrid/gmt_25m_hybrid_z2to10_fourierRectN32
label=gmt_25m_hybrid_z2to10_fourierRectN32
writePupil=false
writeBasis=false
writePhaseScreens=false
