[pupil]
file=/home/jrmales/Source/mxWork/aoAnalysis/dmmask_design_co0.27_pb0.5.fits
name=magaox_6p5m
diameterPixels=48
diameterMeters=6.5
threshold=0.5

[simulation]
trials=10000
oversize=3
wavelength=0.8e-6

[atmosphere]
seeing=0.790
seeingWavelength=500e-9
outerScale=-1
subharmonicLevel=1
outerSubHarmonics=true

[basis]
type=file
file=/home/jrmales/Source/mxWork/aoAnalysis/fklcombo_z10_2400_smoothed_co0.27_pb0.5.fits
name=fklcombo
modes=-1
cutoffs=single
fit=sequential

[analysis]
maxFourierM=25

[output]
directory=output/magaox_6p5m
label=6p5m
writePupil=true
writeBasis=false
writePhaseScreens=true
